services:
  aprs-bbs:
    build: .
    container_name: tc2-aprs-bbs
    volumes:
      - ./config:/config
    restart: unless-stopped
    command: [ "sh", "-c", "/start.sh && python3 /TC2-APRS-BBS/server.py" ]
